2023-01-01 18:24:10,638 DeepLabV3+(ResNet)  INFO: Number of train images: 10270
2023-01-01 18:24:10,639 DeepLabV3+(ResNet)  INFO: Number of validation images: 1784
2023-01-01 18:24:10,639 DeepLabV3+(ResNet)  INFO: Start training
Traceback (most recent call last):
  File "/home/kc/tritd/ResNet/train_fully.py", line 176, in <module>
    model = train(cfg, logger)
  File "/home/kc/tritd/ResNet/train_fully.py", line 97, in train
    for i, (images, labels) in enumerate(train_loader):
  File "/home/kc/.conda/envs/tritd/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/kc/.conda/envs/tritd/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/kc/.conda/envs/tritd/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/kc/.conda/envs/tritd/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/kc/.conda/envs/tritd/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/kc/.conda/envs/tritd/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/home/kc/.conda/envs/tritd/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/kc/.conda/envs/tritd/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 143, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/kc/.conda/envs/tritd/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 143, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/kc/.conda/envs/tritd/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/kc/.conda/envs/tritd/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 163, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 225, 225] at entry 0 and [3, 450, 450] at entry 1